CONST:
  EXP_NAME: panda-cable-finetune
  N_WORKERS: 4

DATASET:
  NAME: null
  PIN_MEMORY: false
  USE_DELTA_ACTION: true
  IMG_SIZE: null
  DELTA_TIMESTAMPS:
    observation: [-2, 0]
  REQUIRED_FEATURES:
    - observation.images.opst_cam
    - observation.images.wrist_cam
    - observation.state
    - action

POLICY:
  TYPE: dynamicvla
  CHECKPOINT: null
  N_OBS_STEPS: 2
  CHUNK_SIZE: 20
  N_ACTION_STEPS: 20
  RESIZE_IMGS_WITH_PADDING: [384, 384]
  ATTENTION_MODE: cross_attn
  VLM_MODEL_NAME: HuggingFaceTB/SmolLM2-360M
  NUM_VLM_LAYERS: 16
  NUM_EXPERT_SKIP_LAYERS: 0
  TEMPORAL_FUSION: attn
  FREEZE_VISION_MODEL: true
  FREEZE_CONNECTOR: true
  FREEZE_TEXT_MODEL: true

DIR:
  OUTPUT: ./runs/panda_cable_finetune

WANDB:
  ENABLED: false
  PROJECT: DynamicVLA-Panda-Cable
  ENTITY: null
  MODE: online
  RUN_ID: null
  LOG_CODE: true
  SYNC_TENSORBOARD: false

TRAIN:
  N_EPOCHS: 30
  BATCH_SIZE: 4
  GRAD_ACCUM_STEPS: 1
  CKPT_SAVE_FREQ:
    EPOCH: 5
    BATCH: 0
  OPTIMIZER:
    LR: 1.0e-5
    EPS: 1.0e-8
    WEIGHT_DECAY: 1.0e-10
    BETAS: [0.9, 0.95]
  LR_SCHEDULER:
    NAME: cosine
    N_WARMUP_STEPS: 200
  IMAGE_TRANSFORMS:
    BRIGHTNESS: [0.8, 1.2]
    CONTRAST: [0.8, 1.2]
    SATURATION: [0.5, 1.5]
    HUE: [-0.05, 0.05]

